version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=100
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - /home/coen/docker/plex/config:/config
      - /home/coen/media/series:/series
      - /home/coen/media/films:/films
      - /home/coen/docker/plex/transcode:/transcode
    restart: unless-stopped
